config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  resources :verifications, only: [:show]
  resources :users do
    match '/resend_verification', to: "verifications#resend", via: :post
  end
  controller :sessions do
    post 'login' => :create
    delete 'logout' => :destroy
  end
  resources :channels do
    resources :rules, only: [:edit, :update]
    resources :subscriptions
    post 'show_modal'
  end
  resources :currencies, only: [:index]
  root 'channels#index'
  resources :quotes, only: [:index]
  resources :trades, only: [:index]
  resources :simulations, only: [:index]
  resources :order_books, only: [:index]
  resources :order_book_items, only: [:index]
  resources :bittrex_market_summaries, only: [:index]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :charts, only: [:index]
  match '/settings',                        to: "users#settings", via: :get
  match '/unsubscribe',                     to: "subscriptions#unsubscribe", via: :get
  match '/charts/:exchange/:currency_pair', to: "charts#show", via: :get
  match '/login',                           to: 'onboarding#login', via: :get
  match '/signup',                          to: 'onboarding#signup', via: :get
  match '/password_reset',                  to: 'onboarding#password_reset', via: :get
  match '/privacy',                         to: 'static_pages#privacy', via: :get
  match '/terms',                           to: 'static_pages#terms', via: :get
  mount Sidekiq::Web, at: '/sidekiq'
end

app/models/channel.rb
class Channel < ActiveRecord::Base
  belongs_to :currency
  has_many :rules, dependent: :destroy
  has_many :subscriptions
  has_many :channel_notifications

  validates :name, presence: true

  accepts_nested_attributes_for :rules, allow_destroy: true

  FREQUENCY_TYPES = ["continuous", "one-time"]

  def self.process_all
    Channel.where(active: true).each do |channel|
      channel.process
    end
  end

  def self.text_search(query)
    currency_id = Currency.where("name @@ :q", q: query).try(:first).try(:id)
    if query.present? && currency_id.present?
      self.where(currency_id: currency_id)
    elsif query.present?
      self.where("name @@ :q or description @@ :q", q: query)
    else
      self.all
    end
  end

  def has_sent_notifications_within_frequency_limit?
    return false unless self.frequency_in_minutes.present?
    self.channel_notifications.where("created_at > ?", DateTime.now - self.frequency_in_minutes.minutes).any?
  end

  def process
    is_passing = false
    self.rules.with_or_operator.each do |rule|
      next if is_passing
      is_passing = rule.is_passing?
    end
    if is_passing
      NotificationsWorker.perform_async(self.id)
      self.deactivate if self.one_time_frequency?
    end
  end

  def deactivate
    self.update_column(:active, false)
  end

  def one_time_frequency?
    self.frequency_type == "one-time"
  end

  def continuous_frequency?
    self.frequency_type == "continuous"
  end
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_action :redirect_non_admin, only: [:new, :create, :edit, :update]

  def index
    if params[:search_value]
      @channels = Channel.text_search(params[:search_value]).where(active: true).paginate(:page => params[:page], :per_page => 9)
    else
      @channels = Channel.where(active: true).paginate(:page => params[:page], :per_page => 9)
    end
  end

  def currencies

  end

  def new
    @channel = Channel.new
    @channel.rules.build
  end

  def create
    @channel = Channel.new(channel_params)
    if @channel.save
      redirect_to new_channel_path, notice: @channel.name + " has been created"
    else
      render 'new'
    end
  end

  def show_modal
    @channel = Channel.find_by_id(params[:channel_id])
  end

  def edit
    @channel = Channel.find_by_id(params[:id])
  end

  def update
    @channel = Channel.find_by_id(params[:id])
    if @channel.update_attributes(channel_params)
      redirect_to edit_channel_path(@channel), notice: "Channel has been updated."
    else
      redirect_to edit_channel_path(@channel), alert: "There was an issue updating this channel."
    end
  end

  private

  def channel_params
    params.require(:channel).permit(:name, :description, :currency_id, :source_name, :source_url, :frequency_in_minutes, :frequency_type,
                    rules_attributes: [:id, :percent_increase, :percent_decrease, :ceiling, :floor, :operator, :custom_function,
                                       :comparison_logic, :lookback_minutes, :comparison_table, :comparison_table_column,
                                       :comparison_table_scope_method, :comparison_table_scope_value])
  end
end

app/helpers/channels_helper.rb
module ChannelsHelper

  def frequency_text(channel)
    if channel.frequency_in_minutes % 60 == 0
      pluralize(channel.frequency_in_minutes/60, "hour")
    else
      pluralize(channel.frequency_in_minutes, "minute")
    end
  end
end

app/views/channels/_channel.html.erb
<div class="channel <%= 'channel-long' if version == 'long' %>">
  <div class="top" style="background: <%= channel.currency.color_hexidecimal %>;">
    <%= show_svg("#{channel.currency.symbol}.svg") %>
    <div class="currency-name">
      <% if channel.currency.name.length > 18 %>
        <%= channel.currency.symbol %>
      <% else %>
        <%= channel.currency.name %>
      <% end %>
      <% if version == 'long' && current_user.present? && current_user.admin? %>
        <%= link_to edit_channel_path(channel) do %>
          <i class="fa fa-edit"></i>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="middle" style="background: <%= channel.currency.color_hexidecimal %>;">
    <div class="name"><%= channel.name.html_safe %></div>
    <% if version == 'long' %>
      <div class="description">
        <%= channel.description.html_safe %>
        <hr>
        <ul class="fa-ul">
          <% if channel.source_name.present? && channel.source_url.present? %>
            <li>
              <i class="fa-li fa fa-database" title="data source"></i>
              <span class="colon">:</span>
              <%= link_to channel.source_url, channel.source_url, target: "_blank" %>
            </li>
          <% end %>
          <li>
            <i class="fa-li fa fa-clock-o" title="frequency of alert logic"></i>
            <span class="colon">:</span>
            refreshed every minute
          </li>
          <li>
            <i class="fa-li fa fa-bell" title="delivery method"></i>
            <span class="colon">:</span>
            via email
            <% if channel.continuous_frequency? %>
              (at most, once every <%= frequency_text(channel) %>)
            <% end %>
          </li>
        </ul>
      </div>
    <% end %>
  </div>
  <div class="bottom">
    <% if current_user.present? %>
      <% on_off = 'on' %>
      <% on_off = 'off' if current_user.subscriptions.where(channel_id: channel.id).any? %>
      <div class="subscription-link-container-channel-<%= channel.id %>">
        <% if on_off == 'on' %>
          <%= render 'channels/on_switch_link', channel: channel %>
        <% elsif on_off == 'off' %>
          <%= render 'channels/off_switch_link', channel: channel %>
        <% end %>
      </div>
    <% else %>
      <%= link_to signup_path do %>
        <%= image_tag('off_switch.png') %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/channels/_close_modal.html.erb
<button type="button" class="close close-channel-modal" data-dismiss="modal" aria-label="Close">
  <i class="fa fa-close fa-2x"></i>
</button>

app/views/channels/_form.html.erb
<%= form_for channel, method: channel.new_record? ? :post : :put do |f| %>
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="form-group">
        <label for="currency_id">Currency</label>
        <%= f.select :currency_id, Currency.with_bittrex_data.order(:name).collect { |c| [ c.name + " (#{c.symbol})", c.id ] }, {}, {style: "width:100%;", class: "form-control"} %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="form-group">
        <label for="name">Name</label>
        <%= f.text_field :name, class: "form-control", placeholder: "Name", required: true %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="form-group">
        <label for="description">Description</label>
        <%= f.text_area :description, class: "form-control", placeholder: "Description", required: true %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="form-group">
        <label for="source_name">Data source name</label>
        <%= f.text_field :source_name, class: "form-control", placeholder: "Data source name" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="form-group">
        <label for="source_url">Data source URL</label>
        <%= f.text_field :source_url, class: "form-control", placeholder: "Data source URL" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 col-sm-6 col-xs-6">
      <div class="form-group">
        <label for="frequency_in_minutes">Frequency of alert (in minutes)</label>
        <%= f.number_field :frequency_in_minutes, class: "form-control", placeholder: "Frequency of alert (in minutes)" %>
      </div>
    </div>
    <div class="col-md-6 col-sm-6 col-xs-6">
      <div class="form-group">
        <label for="frequency_in_minutes">Frequency type</label>
        <%= f.select :frequency_type, Channel::FREQUENCY_TYPES, {}, {style: "width:100%;", class: "form-control"} %>
      </div>
    </div>
  </div>
  <hr>
  <% if channel.new_record? %>
    <h3>Rules:</h3>
    <%= f.fields_for :rules do |ff| %>
      <%= render "rules/form_fields_for", f: ff %>
    <% end %>
  <% end %>
	<%= f.button "#{channel.new_record? ? 'Create' : 'Update'} Channel", data: { disable_with: "<i class='fa fa-circle-o-notch fa-spin'></i> Submitting..." }, class: "btn btn-lg btn-block" %>
<% end %>

app/views/channels/_link_channel.html.erb
<%= link_to channel_show_modal_path(channel), method: :post, remote: true do %>
  <%= render "channels/channel", channel: channel, version: "short" %>
<% end %>

app/views/channels/_modal.html.erb
<div class="modal" id="channelModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <%= render "channels/channel", channel: channel, version: "long" %>
  </div>
</div>

app/views/channels/_off_switch_link.html.erb
<%= link_to "/channels/#{channel.id}/subscriptions/#{current_user.subscriptions.find_by_channel_id(channel.id).try(:id)}", method: :delete, remote: true, class: "subscription-create-link", title: "Turn Off Notification" do %>
  <%= image_tag('on_switch.png') %>
<% end %>

app/views/channels/_on_switch_link.html.erb
<%= link_to channel_subscriptions_path(channel), method: :post, remote: true, class: "subscription-create-link", title: "Turn On Notification" do %>
  <%= image_tag('off_switch.png') %>
<% end %>

app/views/channels/_search_form.html.erb
<div class="search-form-container">
  <%= form_tag channels_path, class: "search-form", method: :get do %>
    <input class="typeahead form-control input-lg" type="text" data-provide="typeahead" required autocomplete="off" placeholder="Search" name="search_value" value="<%= params[:search_value] %>">
    <div class="search-icon-container">
      <i class="fa fa-2x fa-search"></i>
    </div>
    <%= button_tag "Apply filters", class: "btn", data: { disable_with: "Submitting..." }, name: "search", value: "true", style: "display: none;" %>
  <% end %>
</div>

app/views/channels/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-sm-6 col-xs-6 col-md-offset-3 col-sm-offset-3 col-xs-offset-3">
      <h1>Edit Channel</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 col-sm-6 col-xs-6 col-md-offset-3 col-sm-offset-3 col-xs-offset-3">
      <%= link_to "Edit Rule", edit_channel_rule_path(@channel, @channel.rules.first) %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 col-sm-6 col-xs-6 col-md-offset-3 col-sm-offset-3 col-xs-offset-3">
      <hr>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 col-sm-6 col-xs-6 col-md-offset-3 col-sm-offset-3 col-xs-offset-3">
      <%= render "shared/error_messages", object: @channel %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 col-sm-6 col-xs-6 col-md-offset-3 col-sm-offset-3 col-xs-offset-3">
      <%= render 'channels/form', channel: @channel %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 col-sm-6 col-xs-6 col-md-offset-3 col-sm-offset-3 col-xs-offset-3">
      <hr>
    </div>
  </div>
</div>

app/views/channels/index.html.erb
<div class="container-fluid body">
  <div class="row">
    <div class="col-lg-10 col-md-12 col-sm-12 col-xs-12 col-centered">
      <div class="row">
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
          <%= render "channels/search_form" %>
        </div>
      </div>
    </div>
  </div>
  <% unless @channels.any? %>
    <div class="row">
      <div class="col-md-12">
        <div class="center">
          <p>
            <% if params[:search_value] %>
              We could not find anything matching "<%= params[:search_value] %>."
            <% else %>
              No matches found.
            <% end %>
          </p>
          <p><%= link_to "Return Home", root_path %></p>
        </div>
      </div>
    </div>
  <% end %>
  <div class="row">
    <div class="col-lg-10 col-md-12 col-sm-12 col-xs-12 col-centered">
      <div class="row">
        <% @channels.each do |channel| %>
          <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12" style="min-width:330px;">
            <%= render "channels/link_channel", channel: channel %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-10 col-md-12 col-sm-12 col-xs-12 col-centered">
      <div class="center">
        <%= will_paginate @channels, renderer: BootstrapPagination::Rails %>
      </div>
    </div>
  </div>
</div>

<%= render "layouts/footer" %>
<div id="channel-modal-container">
</div>

app/views/channels/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-sm-6 col-xs-6 col-md-offset-3 col-sm-offset-3 col-xs-offset-3">
      <h1>New Channel</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 col-sm-6 col-xs-6 col-md-offset-3 col-sm-offset-3 col-xs-offset-3">
      <hr>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 col-sm-6 col-xs-6 col-md-offset-3 col-sm-offset-3 col-xs-offset-3">
      <%= render "shared/error_messages", object: @channel %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 col-sm-6 col-xs-6 col-md-offset-3 col-sm-offset-3 col-xs-offset-3">
      <%= render 'channels/form', channel: @channel %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 col-sm-6 col-xs-6 col-md-offset-3 col-sm-offset-3 col-xs-offset-3">
      <hr>
    </div>
  </div>
</div>

app/views/channels/show_modal.js.erb
$("#channel-modal-container").html("<%= escape_javascript(render 'channels/modal', channel: @channel) %>");
$("#channel-modal-container").prepend("<%= escape_javascript(render 'channels/close_modal') %>");
$('#channelModal').modal('show');

channelModalActions();