config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  resources :verifications, only: [:show]
  resources :users do
    match '/resend_verification', to: "verifications#resend", via: :post
  end
  controller :sessions do
    post 'login' => :create
    delete 'logout' => :destroy
  end
  resources :channels do
    resources :rules, only: [:edit, :update]
    resources :subscriptions
    post 'show_modal'
  end
  resources :currencies, only: [:index]
  root 'channels#index'
  resources :quotes, only: [:index]
  resources :trades, only: [:index]
  resources :simulations, only: [:index]
  resources :order_books, only: [:index]
  resources :order_book_items, only: [:index]
  resources :bittrex_market_summaries, only: [:index]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :charts, only: [:index]
  match '/settings',                        to: "users#settings", via: :get
  match '/unsubscribe',                     to: "subscriptions#unsubscribe", via: :get
  match '/charts/:exchange/:currency_pair', to: "charts#show", via: :get
  match '/login',                           to: 'onboarding#login', via: :get
  match '/signup',                          to: 'onboarding#signup', via: :get
  match '/password_reset',                  to: 'onboarding#password_reset', via: :get
  match '/privacy',                         to: 'static_pages#privacy', via: :get
  match '/terms',                           to: 'static_pages#terms', via: :get
  mount Sidekiq::Web, at: '/sidekiq'
end

app/controllers/onboarding_controller.rb
class OnboardingController < ApplicationController
  before_action :redirect_signed_in_user

  def login
  end

  def signup
    @new_user = User.new
  end

  def password_reset
  end
end

app/helpers/onboarding_helper.rb
module OnboardingHelper
end

app/views/onboarding/rows/_agreement_text.html.erb
<div class="row">
  <div class="col-md-12 col-sm-12 col-xs-12">
    <small>
      By signing up I agree to <%= t('application.root.name') %>'s <%= link_to "Terms of Service", terms_path %> and <%= link_to "Privacy Policy", privacy_path %>.
    </small>
  </div>
</div>

app/views/onboarding/rows/_already_have_account.html.erb
<div class="row">
  <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3 col-sm-offset-3">
    <label>
      Already have an account?
      <%= link_to "Log in", login_path %>
    </label>
  </div>
</div>

app/views/onboarding/rows/_dont_have_account.html.erb
<div class="row">
  <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3 col-sm-offset-3">
    <label>
      Don't have an account?
      <%= link_to "Sign up", signup_path %>
    </label>
  </div>
</div>

app/views/onboarding/rows/_or_divider.html.erb
<div class="row top-margin-small bottom-margin-small">
  <div class="col-md-5 col-sm-5 col-xs-5 no-right-padding">
    <hr>
  </div>
  <div class="col-md-2 col-sm-2 col-xs-2 no-side-padding">
    <div class="or-divider">
      or
    </div>
  </div>
  <div class="col-md-5 col-sm-5 col-xs-5 no-left-padding">
    <hr>
  </div>
</div>